### ISSUE TITLE
No menuoption in treeview on atom1.19.0

### ISSUE THREAD

**Issue by ZemanekRadek** [yongkangchen/remote-sync#433]
No menuoption in treeview on atom1.19.0

hotfix https://github.com/yongkangchen/remote-sync/issues/388#issuecomment-302121984 not working, please, help me!

**Comment by philchanet** [comment]
The fix described here also works with versions 1.18 and 1.19 of Atom: #388

**Comment by mihrich** [comment]
Sorry. "v1.19.5" no menuoption too. Version package is "remote-sync 4.15"

**Comment by daverickdunn** [comment]
I've created a pull request for this issue: https://github.com/yongkangchen/remote-sync/pull/438

If you want to fix it manually, then open remote-sync/menus/context.cson and change the following:

`'atom-text-editor, .tree-view .full-menu .file'` to `'.entries.list-tree .file.entry.list-item'`

and

`'.tree-view .full-menu .header.list-item'` to `'.entries.list-tree .header.list-item, .entries.list-tree .directory.entry.list-nested-item.collapsed'`

**Comment by daverickdunn** [comment]
On closer inspection, it appears that the changes made to resolve the issue in Atom 1.17 have been reverted to what they were before this commit: https://github.com/yongkangchen/remote-sync/pull/400

Those selectors seem to still work, so by all means use them instead of my pull request, but please use either.

**Comment by daverickdunn** [comment]
This has now been merged and a patch released... https://github.com/yongkangchen/remote-sync/commit/3432d5287fa035dea822e7a7599bab62454cdf69
